# Generated by Django 4.2.7 on 2023-12-06 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_categoryproduct_measureunit_alter_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryproduct',
            name='measure_unit',
        ),
    ]
