# Generated by Django 4.2.7 on 2023-12-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_categoryproduct_measure_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalMeasureUnit',
        ),
    ]
