# Generated by Django 4.2.7 on 2023-12-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_delete_historicalmeasureunit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryproduct',
            options={'verbose_name': 'Categoría de Producto', 'verbose_name_plural': 'Categorías de Productos'},
        ),
        migrations.AlterField(
            model_name='categoryproduct',
            name='description',
            field=models.CharField(max_length=50, unique=True, verbose_name='Descripcion'),
        ),
    ]
