# Generated by Django 4.2.7 on 2023-12-06 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_categoryproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalindicador',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Indicador', 'verbose_name_plural': 'historical Indicadores'},
        ),
        migrations.AlterModelOptions(
            name='indicador',
            options={'verbose_name': 'Indicador', 'verbose_name_plural': 'Indicadores'},
        ),
    ]
